name: Trigger Frontend Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # Enable manual triggering
  workflow_dispatch:

jobs:
  trigger-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger frontend repository tests
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.FRONTEND_REPO_PAT }}
          repository: RajRavi05/cross-repo-test
          event-type: backend-push
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
